# Generated by Django 5.1 on 2024-08-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='data_proxima_manutencao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='data_ultima_manutencao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='nome',
            field=models.CharField(default='Equipamento sem nome', max_length=255),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('em_uso', 'Em Uso'), ('em_estoque', 'Em Estoque'), ('manutencao', 'Em Manutenção'), ('nao_funcional', 'Não Funcional')], default='em_estoque', max_length=50),
        ),
    ]
