# Generated by Django 5.1 on 2024-09-01 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0002_equipamento_data_proxima_manutencao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='data_compra',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='fabricante',
            field=models.CharField(default='Fabricante desconhecido', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='modelo',
            field=models.CharField(default='Modelo desconhecido', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='numero_serie',
            field=models.CharField(default='Número de série desconhecido', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='tipo',
            field=models.CharField(default='Equipamento sem tipo', max_length=100),
        ),
    ]
