version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    image: samuelamt/crud-equipamentos:latest
    container_name: equipamentos-crud-container
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env.local
